spring:
  redis:
    host: henghe-034
    port: 6379
    password: root

redisson:
  redis:
    address: redis://192.168.101.34:6379
    password: root

zookeeper:
  client:
    address: 192.168.101.33:2181